# Cowsay Container - v0.5
# 從已存在的檔案複製
FROM alpine:latest

MAINTAINER fangpapa

RUN apk add --no-cache perl

COPY cowsay /usr/bin/cowsay
COPY default.cow /usr/share/cowsay/default.cow

CMD ["/usr/bin/cowsay","Docker is very good !"]
