# Cowsay Container - v0.3.1
FROM centos:latest

MAINTAINER fangpapa

RUN yum -y update
RUN yum install -y epel-release
RUN yum install -y cowsay
RUN yum clean all
RUN dd if=/dev/zero of=/tmp/1G-file bs=1M count=1024 && rm -rf /var/cache/yum /var/tmp/* /tmp/*

CMD ["/usr/bin/cowsay","Docker is very good !"]
